### ISSUE TITLE
(bug): changing active window does not take effect

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltoscluster-manager#222]
Once the activeWindow is set, changing it does not take effect 

For instance set ActiveWindow

```yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: SveltosCluster
metadata:
  name: cluster1
  namespace: civo
spec:
  activeWindow:
    from: 0 20 * * 5
    to: 0 7 * * 1
  consecutiveFailureThreshold: 3
  paused: true
```

we can see Status is correctly set

```yaml
status:
  connectionStatus: Healthy
  nextPause: "2024-08-26T07:00:00Z"
  nextUnpause: "2024-08-23T20:00:00Z"
```

If we now change the activeWindow 

```yaml
spec:
  activeWindow:
    from: 30 10 * * *
    to: 0 11 * * *
```

Status is not updated. It will only be updated once once first unpause window is hit.

Change is limited to this [function](https://github.com/projectsveltos/sveltoscluster-manager/blob/d81667c0311e5766d6b3526cf643b63ae0bae169/controllers/sveltoscluster_controller.go#L414C33-L415C4)
